### ISSUE TITLE
segfault when going through the tut3d tutorial 'plow right metal1'

### ISSUE THREAD

**Issue by smunaut** [RTimothyEdwards/magic#27]
Back trace :

```
Thread 1 "wish" received signal SIGSEGV, Segmentation fault.
0x00007f3b1892056d in dbCopyDefFunc (use=0x7f3b188d7630, def=0x7ffd9b525db0) at DBcellsubr.c:149
149	    use->cu_parent = def;
(gdb) bt
#0  0x00007f3b1892056d in dbCopyDefFunc (use=0x7f3b188d7630, def=0x7ffd9b525db0) at DBcellsubr.c:149
#1  0x00007f3b1891be99 in DBSrCellPlaneArea (plane=0x55f6b9fb8750, rect=0x7f3b18b38f20 <TiPlaneRect>, 
    func=0x7f3b18920555 <dbCopyDefFunc>, arg=140727209319856) at DBcellsrch.c:91
#2  0x00007f3b18920543 in DBCellCopyDefBody (sourceDef=0x55f6ba2b60d0, destDef=0x7ffd9b525db0) at DBcellsubr.c:139
#3  0x00007f3b18a18524 in plowYankMore (area=0x7ffd9b5261c0, halo=14, back=1) at PlowYank.c:194
#4  0x00007f3b18a082fa in plowApplySearchRules (edge=0x7ffd9b5261c0) at PlowMain.c:1660
#5  0x00007f3b18a08267 in plowProcessEdge (edge=0x7ffd9b5261c0, changedArea=0x7ffd9b526290) at PlowMain.c:1620
#6  0x00007f3b18a06da8 in plowPropagateRect (def=0x55f6bb6e2be0, userRect=0x7ffd9b526370, lc=..., changedArea=0x7ffd9b526290)
    at PlowMain.c:763
#7  0x00007f3b18a06667 in Plow (def=0x55f6bb6e2be0, userRect=0x7ffd9b526370, layers=..., direction=3) at PlowMain.c:521
#8  0x00007f3b18a0468b in CmdPlow (w=0x55f6ba484a10, cmd=0x55f6bb7aea70) at PlowCmd.c:209
#9  0x00007f3b189db01c in WindExecute (w=0x55f6ba484a10, rc=94518184207856, cmd=0x55f6bb7aea70) at windMain.c:414
#10 0x00007f3b189516ce in DBWcommands (w=0x55f6ba484a10, cmd=0x55f6bb7aea70) at DBWprocs.c:598
#11 0x00007f3b189d78ce in WindSendCommand (w=0x55f6ba484a10, cmd=0x55f6bb7aea70, quiet=1 '\001') at windSend.c:263
#12 0x00007f3b189cf97f in TxTclDispatch (clientData=0x0, argc=3, argv=0x55f6ba06e8a0, quiet=1 '\001') at txCommands.c:1180
#13 0x00007f3b18ae0e58 in _tcl_dispatch (clientData=0x0, interp=0x55f6ba06cf70, argc=3, argv=0x55f6ba06e8a0) at tclmagic.c:400
#14 0x00007f3b1a9719ab in TclInvokeStringCommand () from /lib/x86_64-linux-gnu/libtcl8.6.so
#15 0x00007f3b1a973777 in TclNRRunCallbacks () from /lib/x86_64-linux-gnu/libtcl8.6.so
#16 0x00007f3b1aa166a2 in ?? () from /lib/x86_64-linux-gnu/libtcl8.6.so
#17 0x00007f3b1aa13f57 in ?? () from /lib/x86_64-linux-gnu/libtcl8.6.so
#18 0x00007f3b1a973777 in TclNRRunCallbacks () from /lib/x86_64-linux-gnu/libtcl8.6.so
#19 0x00007f3b1a974b6f in ?? () from /lib/x86_64-linux-gnu/libtcl8.6.so
--Type <RET> for more, q to quit, c to continue without paging--
#20 0x00007f3b1a9744d3 in Tcl_EvalEx () from /lib/x86_64-linux-gnu/libtcl8.6.so
#21 0x00007f3b1ab2512d in Tk_BindEvent () from /lib/x86_64-linux-gnu/libtk8.6.so
#22 0x00007f3b1ab2bebf in TkBindEventProc () from /lib/x86_64-linux-gnu/libtk8.6.so
#23 0x00007f3b1ab34523 in Tk_HandleEvent () from /lib/x86_64-linux-gnu/libtk8.6.so
#24 0x00007f3b1ab34cb0 in ?? () from /lib/x86_64-linux-gnu/libtk8.6.so
#25 0x00007f3b1aa3b78f in Tcl_ServiceEvent () from /lib/x86_64-linux-gnu/libtcl8.6.so
#26 0x00007f3b1aa3b9f5 in Tcl_DoOneEvent () from /lib/x86_64-linux-gnu/libtcl8.6.so
#27 0x00007f3b1ab35112 in Tk_MainLoop () from /lib/x86_64-linux-gnu/libtk8.6.so
#28 0x00007f3b1ab44197 in Tk_MainEx () from /lib/x86_64-linux-gnu/libtk8.6.so
#29 0x000055f6b8e930dc in ?? ()
#30 0x00007f3b1a76f1e3 in __libc_start_main (main=0x55f6b8e930b0, argc=6, argv=0x7ffd9b527008, init=<optimized out>, 
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffd9b526ff8) at ../csu/libc-start.c:308
#31 0x000055f6b8e9311a in _start ()
```

**Comment by RTimothyEdwards** [comment]
Thank you for reporting this and for providing the backtrace, which was very helpful.  This was a loose end left over from the "bplane" implementation from a few months ago, just a simple missing variable initialization.  The routine had not been exercised because I did not realize that it is only called from within the "plow" code.  After fixing, I verified that the tutorial command "plow right metal1" works.  I have pushed the fix to the opencircuitdesign.com repo, and the tarball and github repo will be updated overnight tonight.
